-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.agua_disponibilidade_e_tratamento
(
    agua_disponibilidade_e_tratamento_pais_nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    precipitacao_milhoes_de_metros_cubicos_por_ano real,
    agua_suja_gerada_em_1000_metros_cubicos_por_dia real,
    agua_suja_nao_tratada_em_1000_metros_cubicos_por_dia real,
    CONSTRAINT pk_agua_disponibilidade_e_tratamento PRIMARY KEY (agua_disponibilidade_e_tratamento_pais_nome)
);

CREATE TABLE IF NOT EXISTS public.pais
(
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    numero_de_habitantes_em_milhares integer NOT NULL,
    CONSTRAINT pk_nome PRIMARY KEY (nome)
);

CREATE TABLE IF NOT EXISTS public.saneamento
(
    saneamento_pais_nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    porcentagem_urbana_com_acesso_a_instalacoes_basicas real,
    porcentagem_rural_com_acesso_a_instalacoes_basicas real,
    taxa_de_morte_a_cada_100000_mortes_devido_a_sanitacao_nao_segur real,
    CONSTRAINT pk_saneamento PRIMARY KEY (saneamento_pais_nome)
);

CREATE TABLE IF NOT EXISTS public.higiene
(
    higiene_pais_nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    porcentagem_urbana_com_acesso_a_instalacoes_basicas real,
    porcentagem_rural_com_acesso_a_instalacoes_basicas real,
    taxa_de_morte_a_cada_100000_mortes_devido_a_falta_instalacoes_d real,
    CONSTRAINT pk_higiene PRIMARY KEY (higiene_pais_nome)
);

CREATE TABLE IF NOT EXISTS public.agua_potavel
(
    agua_potavel_pais_nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    porcentagem_urbana_com_acesso_a_instalacoes_basicas real,
    porcentagem_rural_com_acesso_a_instalacoes_basicas real,
    taxa_de_morte_a_cada_100000_mortes_devido_a_agua_nao_segura real,
    CONSTRAINT pk_agua_potavel PRIMARY KEY (agua_potavel_pais_nome)
);

CREATE TABLE IF NOT EXISTS public.economia
(
    economia_pais_nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    taxa_de_desemprego real,
    gini real,
    pib_per_capita real,
    CONSTRAINT pk_economia PRIMARY KEY (economia_pais_nome)
);

CREATE TABLE IF NOT EXISTS public.qualidade_de_vida
(
    qualidade_de_vida_pais_nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    idh real,
    expectativa_de_vida real,
    CONSTRAINT pk_qualidade_de_vida PRIMARY KEY (qualidade_de_vida_pais_nome)
);

CREATE TABLE IF NOT EXISTS public.emissao_gases
(
    emissao_gases_pais_nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    emissao_n2o_em_quilotoneladas_por_ano real,
    emissao_co2_em_quilotoneladas_por_ano real,
    emissao_ch4_em_quilotoneladas_por_ano real,
    CONSTRAINT pk_emissao_gases PRIMARY KEY (emissao_gases_pais_nome)
);

CREATE TABLE IF NOT EXISTS public.desenvolvimento_da_area_da_saude
(
    desenvolvimento_da_area_da_saude_pais_nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    numero_de_casos_de_colera integer,
    taxa_de_medicos_a_cada_1000_cidadaos real,
    numero_de_camas_hospitalares_a_cada_10000_cidadaos real,
    CONSTRAINT pk_desenvolvimento_da_area_da_saude PRIMARY KEY (desenvolvimento_da_area_da_saude_pais_nome)
);

ALTER TABLE IF EXISTS public.agua_disponibilidade_e_tratamento
    ADD CONSTRAINT fk07_agua_disponibilidade_e_tratamento FOREIGN KEY (agua_disponibilidade_e_tratamento_pais_nome)
    REFERENCES public.pais (nome) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS pk_agua_disponibilidade_e_tratamento
    ON public.agua_disponibilidade_e_tratamento(agua_disponibilidade_e_tratamento_pais_nome);


ALTER TABLE IF EXISTS public.saneamento
    ADD CONSTRAINT fk01_pais_saneamento FOREIGN KEY (saneamento_pais_nome)
    REFERENCES public.pais (nome) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS pk_saneamento
    ON public.saneamento(saneamento_pais_nome);


ALTER TABLE IF EXISTS public.higiene
    ADD CONSTRAINT fk02_pais_higiene FOREIGN KEY (higiene_pais_nome)
    REFERENCES public.pais (nome) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS pk_higiene
    ON public.higiene(higiene_pais_nome);


ALTER TABLE IF EXISTS public.agua_potavel
    ADD CONSTRAINT fk03_pais_agua_potavel FOREIGN KEY (agua_potavel_pais_nome)
    REFERENCES public.pais (nome) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS pk_agua_potavel
    ON public.agua_potavel(agua_potavel_pais_nome);


ALTER TABLE IF EXISTS public.economia
    ADD CONSTRAINT fk04_pais_economia FOREIGN KEY (economia_pais_nome)
    REFERENCES public.pais (nome) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS pk_economia
    ON public.economia(economia_pais_nome);


ALTER TABLE IF EXISTS public.qualidade_de_vida
    ADD CONSTRAINT fk05_pais_qualidade_de_vida FOREIGN KEY (qualidade_de_vida_pais_nome)
    REFERENCES public.pais (nome) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS pk_qualidade_de_vida
    ON public.qualidade_de_vida(qualidade_de_vida_pais_nome);


ALTER TABLE IF EXISTS public.emissao_gases
    ADD CONSTRAINT fk06_emissao_gases FOREIGN KEY (emissao_gases_pais_nome)
    REFERENCES public.pais (nome) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS pk_emissao_gases
    ON public.emissao_gases(emissao_gases_pais_nome);


ALTER TABLE IF EXISTS public.desenvolvimento_da_area_da_saude
    ADD CONSTRAINT fk08_desenvolvimento_da_area_da_saude FOREIGN KEY (desenvolvimento_da_area_da_saude_pais_nome)
    REFERENCES public.pais (nome) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS pk_desenvolvimento_da_area_da_saude
    ON public.desenvolvimento_da_area_da_saude(desenvolvimento_da_area_da_saude_pais_nome);

END;

SELECT
	CASE
		WHEN e.PIB_per_capita > 30000 THEN 'País de Alta Renda'
		WHEN e.PIB_per_capita > 10000 THEN 'País de Média Renda'
		WHEN e.PIB_per_capita > 0 THEN 'País de Baixa Renda'
		ELSE 'Desconhecido'
	END AS desenvolvimento,
	AVG(s.porcentagem_urbana_com_acesso_a_instalacoes_basicas) AS media_urbana_acesso
FROM saneamento s
INNER JOIN economia e ON s.saneamento_pais_nome = e.economia_pais_nome
GROUP BY desenvolvimento
ORDER BY media_urbana_acesso DESC;

SELECT
	CASE
		WHEN a.taxa_de_morte_a_cada_100000_mortes_devido_a_agua_nao_segura > 30000 THEN 'País com Muita Chuva'
		WHEN a.taxa_de_morte_a_cada_100000_mortes_devido_a_agua_nao_segura > 10000 THEN 'País com Moderada Chuva'
		WHEN a.taxa_de_morte_a_cada_100000_mortes_devido_a_agua_nao_segura > 0 THEN 'País com Pouca Chuva'
		ELSE 'Desconhecido'
	END AS ,
	AVG(d.numero_de_casos_de_colera/p.numero_de_habitantes_em_milhares) AS media_taxa_colera
FROM agua_potavel a
INNER JOIN desenvolvimento_da_area_da_saude d ON a.agua_potavel_pais_nome = d.desenvolvimento_da_area_da_saude_pais_nome
INNER JOIN pais p ON a.agua_potavel_pais_nome = p.nome
GROUP BY 
ORDER BY media_taxa_de_morte_a_cada_100000_morte_por_agua_nao_segura DESC;
